version: '3.8'

services:
  # --- Zookeeper for Kafka ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # --- Kafka Broker ---
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # --- RocketMQ NameServer ---
  rmq-namesrv:
    image: apache/rocketmq:5.1.4
    container_name: rmq-namesrv
    command: sh mqnamesrv
    ports:
      - "9876:9876"

  # --- RocketMQ Broker ---
  rmq-broker:
    image: apache/rocketmq:5.1.4
    container_name: rmq-broker
    depends_on:
      - rmq-namesrv
    command: sh mqbroker -n rmq-namesrv:9876 -c /opt/rocketmq/conf/broker.conf
    ports:
      - "10911:10911"
      - "10909:10909"
    volumes:
      - ./broker.conf:/opt/rocketmq/conf/broker.conf
